name: servant-aeson-specs
version: "0.1"
synopsis: generic tests for aeson serialization in servant
description: tests for aeson serialization in servant
category: Web
maintainer: soenkehahn@gmail.com
license: BSD3
license-file: LICENSE

github: plow-technologies/servant-aeson-specs

dependencies:
  - base < 5
  - aeson
  - bytestring
  - hspec
  - QuickCheck
  - servant == 0.4.*

ghc-options:
  -Wall -fno-warn-name-shadowing

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec-core
      - temporary
      - doctest

library:
  source-dirs:
    - src
