name: servant-aeson-specs
version: "0.1"

dependencies:
  - base < 5
  - aeson
  - bytestring
  - hspec
  - QuickCheck
  - servant == 0.4.*

ghc-options:
  -Wall -fno-warn-name-shadowing

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec-core
      - temporary
      - doctest

library:
  source-dirs:
    - src
