name: servant-aeson-specs
version: "0.4.1"
synopsis: generic tests for aeson serialization in servant
description: tests for aeson serialization in servant
category: Web
maintainer: soenkehahn@gmail.com
license: MIT
license-file: LICENSE

github: plow-technologies/servant-aeson-specs

dependencies:
  - base < 5
  - aeson
  - bytestring
  - hspec
  - QuickCheck
  - servant == 0.4.* || == 0.5.* || == 0.6.* || == 0.7.* || == 0.8.*
  - directory
  - filepath
  - random
  - aeson-pretty
  - quickcheck-arbitrary-adt == 0.2.0.0
  - hspec-golden-aeson == 0.2.0.1

ghc-options:
  -Wall -fno-warn-name-shadowing

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec-core
      - temporary
      - doctest
      - mockery
      - silently
      - quickcheck-instances
      - string-conversions
      - text
      - quickcheck-arbitrary-adt == 0.2.0.0
      - hspec-golden-aeson == 0.2.0.1

library:
  source-dirs:
    - src
