name: servant-aeson-specs
version: "0.2"
synopsis: generic tests for aeson serialization in servant
description: tests for aeson serialization in servant
category: Web
maintainer: soenkehahn@gmail.com
license: MIT
license-file: LICENSE

github: plow-technologies/servant-aeson-specs

dependencies:
  - base < 5
  - aeson
  - bytestring
  - hspec
  - QuickCheck
  - servant == 0.4.*
  - directory
  - filepath
  - random
  - aeson-pretty

ghc-options:
  -Wall -fno-warn-name-shadowing

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec-core
      - temporary
      - doctest
      - mockery
      - silently
      - quickcheck-instances
      - string-conversions
      - text

library:
  source-dirs:
    - src
